local die1 = display.newImage("die1.png", display.contentCenterX, display.contentCenterY - (48 * 2))
local die2 = display.newImage("die2.png", display.contentCenterX, display.contentCenterY - (48))
local die3 = display.newImage("die3.png", display.contentCenterX, display.contentCenterY )
local die4 = display.newImage("die4.png", display.contentCenterX, display.contentCenterY + (48))
local die5 = display.newImage("die5.png", display.contentCenterX, display.contentCenterY + (48) * 2)
local die6 = display.newImage("die6.png", display.contentCenterX, display.contentCenterY + (48) * 3)
